### ISSUE TITLE
ワイヤーフレームの作成

### ISSUE THREAD

**Issue by tkuramot** [recursion-team-a/card-games#2]

**Comment by KoshinHagimoto** [comment]
## 行ったこと
[figma](https://www.figma.com/file/BWZhroSQU0W5CUFdYzOmPb/Recursion-Card-game?type=design&node-id=0%3A1&t=aoKqPbA2dPEpaTCw-1)を利用して仮でワイヤーフレームを作成してみました.
最低限の機能要件は実現するようにしましたが, 構成や機能面で修正があればコメントお願いいたします。

**Comment by tkuramot** [comment]
figma上でアクセス権をリクエストしました。

**Comment by KoshinHagimoto** [comment]
承認しました.
