### ISSUE TITLE
基本的な画面遷移 6/9

### ISSUE THREAD

**Issue by tkuramot** [recursion-team-a/card-games#23]

**Comment by tkuramot** [comment]
Phaser, Next.js

**Comment by takatokawazu** [comment]
・ページ遷移機能
ホーム画面、ゲーム選択画面、各ゲームの画面、ルール画面までのルーティングはしました。ただ、各ゲームでphaserを描画するのはまだできていません。
前回プロトタイプで作ったものと比べるとなるべくコンポーネントなどを使い、再利用性のあるコードにしました。
https://zenn.dev/akfm/articles/next-app-router-navigation 

・Pharser 画面表示
NextjsとPhaserjsの連携。
Nextjsでは、デフォルトでサーバーサイドレンダリングになっているため、window操作ができない。そのため、サーバーサイドレンダリングの機能をfalseにするか、動的にimportするか。Nextjs13でApp Routerを使っているため、ネットの記事などで拾った情報と少し異なる部分があるかもしれない。
