### ISSUE TITLE
jestの調査 6/9

### ISSUE THREAD

**Issue by tkuramot** [recursion-team-a/card-games#27]

**Comment by takatokawazu** [comment]
この記事がjestについて全く知らなくてもわかりやすかったです。
https://qiita.com/katu_/items/6c4fab16f5f2be30ce42

Jest 使い方

npm install --save-dev jest

例 /sum.js
function sum(a, b) {
  return a + b;
}
module.exports = sum;

例 /sum.test.js
const sum = require('./sum');

test('adds 1 + 2 to equal 3', () => {
  expect(sum(1, 2)).toBe(3);
});

Package.json に追加するして、npm testで実行可能。
他にも様々な関数があるため、随時調べる。
