### ISSUE TITLE
テーブル画像

### ISSUE THREAD

**Issue by tkuramot** [recursion-team-a/card-games#43]
背景の透過。チップについては個別の画像ファイル

**Comment by tkuramot** [comment]
テーブルの素材です。後々、スマホ対応とかの可能性もあるので、テーブルをそのまま使うよりは単一の柄とか色にしたほうが扱いやすいような気がしています
1. https://www.freepik.com/free-photo/dark-green-texture_973582.htm#query=solid%20green%20background&position=11&from_view=search&track=ais
2. https://www.freepik.com/free-photo/green-painted-smooth-textured-background_16013285.htm#query=solid%20green%20background&position=20&from_view=search&track=ais
3. https://www.freepik.com/free-photo/dark-green-wall_4246302.htm#query=green%20felt%20background&position=20&from_view=keyword&track=ais
4. https://www.freepik.com/free-vector/green-geometric-background-patricks-day-colors_5685388.htm#query=poker%20table%20texture&position=10&from_view=keyword&track=ais

**Comment by KoshinHagimoto** [comment]
確かにテーブルの画像より、シンプルなほうが扱いがしやすそうですね

**Comment by takatokawazu** [comment]
そうですね、とりあえず反映させます。

**Comment by tkuramot** [comment]
https://www.vecteezy.com/vector-art/6325236-poker-table-green-cloth-on-dark-background-vector-illustration
https://www.vecteezy.com/vector-art/24232274-green-casino-poker-table-texture-game-background
https://www.vecteezy.com/free-vector/poker-table

**Comment by tkuramot** [comment]
- 単色
    - 緑色
    - 灰色
- 柄
    - 今使っているもの
    - https://www.vecteezy.com/vector-art/24232274-green-casino-poker-table-texture-game-background
    - https://www.vecteezy.com/vector-art/6325236-poker-table-green-cloth-on-dark-background-vector-illustration
    - https://online.bestfreegame.com/onlinegame-8289.php

**Comment by KoshinHagimoto** [comment]
https://casualpixel.itch.io/pixel-blackjack
